### PR TITLE
output example for parameter 19937-2

### PR DESCRIPTION
**Pull request by majiang**
This PR is not for merging.

### CODE REVIEW

**Comment by majiang** [comment]
@MSaito When you have time could you kindly check the output for the parameters in the second row: [32 bit](https://github.com/majiang/sfmtd/blob/87ad7e202fede433ea4e094a2423e39b42dbfc21/sfmt19937-32.out) and (https://github.com/majiang/sfmtd/blob/87ad7e202fede433ea4e094a2423e39b42dbfc21/sfmt19937-64.out)[64 bit]?

**Comment by MSaito** [comment]
They seem to be different.
my outputs are:
[test32.out.txt](https://github.com/majiang/sfmtd/files/1381540/test32.out.txt)
[test64.out.txt](https://github.com/majiang/sfmtd/files/1381541/test64.out.txt)

**Comment by majiang** [comment]
Thanks! Found the bug which should be fixed by #5.

**Comment by majiang** [comment]
Merged and re-generated the output example. Now it seems correct. Thanks @MSaito!

**Comment by majiang** [comment]
Now #3 is enough.

**Pull request closed without merging**
